export interface OnboardingStepDefinition {
  key: string;
  name: string;
  description?: string;
  order: number;
  isRequired: boolean;
  isSkippable: boolean;
  dependencies?: string[];
}

export const USER_ONBOARDING_STEPS: OnboardingStepDefinition[] = [
  {
    key: 'email_verification',
    name: 'Email Verification',
    description: 'Verify your email address',
    order: 1,
    isRequired: true,
    isSkippable: false,
  },
  {
    key: 'profile_completion',
    name: 'Profile Completion',
    description: 'Complete your personal profile',
    order: 2,
    isRequired: true,
    isSkippable: false,
  },
  {
    key: 'security_setup',
    name: 'Security Setup',
    description: 'Set up 2FA and security questions',
    order: 3,
    isRequired: true,
    isSkippable: true,
  },
  {
    key: 'kyc_submission',
    name: 'KYC Submission',
    description: 'Submit identity verification documents',
    order: 4,
    isRequired: true,
    isSkippable: false,
    dependencies: ['profile_completion'],
  },
  {
    key: 'kyc_approval',
    name: 'KYC Approval',
    description: 'Wait for identity verification approval',
    order: 5,
    isRequired: true,
    isSkippable: false,
    dependencies: ['kyc_submission'],
  },
  {
    key: 'initial_settings',
    name: 'Initial Settings',
    description: 'Configure your preferences',
    order: 6,
    isRequired: false,
    isSkippable: true,
  },
  {
    key: 'first_action',
    name: 'First Action',
    description: 'Perform your first platform action',
    order: 7,
    isRequired: false,
    isSkippable: true,
  },
  {
    key: 'tutorial_completion',
    name: 'Tutorial Completion',
    description: 'Complete the interactive tutorial',
    order: 8,
    isRequired: false,
    isSkippable: true,
  },
  {
    key: 'app_download',
    name: 'App Download',
    description: 'Download mobile application',
    order: 9,
    isRequired: false,
    isSkippable: true,
  },
  {
    key: 'referral_invite',
    name: 'Invite Friends',
    description: 'Invite colleagues to the platform',
    order: 10,
    isRequired: false,
    isSkippable: true,
  },
];

export const TENANT_ONBOARDING_STEPS: OnboardingStepDefinition[] = [
  {
    key: 'plan_selection',
    name: 'Plan Selection',
    description: 'Select a subscription plan',
    order: 0,
    isRequired: true,
    isSkippable: false,
  },
  {
    key: 'tenant_registration',
    name: 'Organization Registration',
    description: 'Register your organization',
    order: 1,
    isRequired: true,
    isSkippable: false,
    dependencies: ['plan_selection'],
  },
  {
    key: 'admin_creation',
    name: 'Admin Account Setup',
    description: 'Create administrator account',
    order: 2,
    isRequired: true,
    isSkippable: false,
    dependencies: ['tenant_registration'],
  },
  {
    key: 'domain_configuration',
    name: 'Domain Configuration',
    description: 'Configure custom domain',
    order: 3,
    isRequired: false,
    isSkippable: true,
  },
  {
    key: 'schema_initialization',
    name: 'Schema Initialization',
    description: 'Initialize database schema',
    order: 4,
    isRequired: true,
    isSkippable: false,
    dependencies: ['admin_creation'],
  },
  {
    key: 'payment_setup',
    name: 'Payment Setup',
    description: 'Configure billing information',
    order: 5,
    isRequired: true,
    isSkippable: true,
  },
  {
    key: 'branding_configuration',
    name: 'Branding Configuration',
    description: 'Customize organization branding',
    order: 6,
    isRequired: false,
    isSkippable: true,
  },
  {
    key: 'initial_settings',
    name: 'Initial Settings',
    description: 'Configure organization settings',
    order: 7,
    isRequired: true,
    isSkippable: false,
  },
  {
    key: 'team_invitation',
    name: 'Team Invitation',
    description: 'Invite team members',
    order: 8,
    isRequired: false,
    isSkippable: true,
  },
  {
    key: 'compliance_setup',
    name: 'Compliance Setup',
    description: 'Configure compliance policies',
    order: 9,
    isRequired: true,
    isSkippable: true,
  },
  {
    key: 'integration_setup',
    name: 'Integration Setup',
    description: 'Connect third-party services',
    order: 10,
    isRequired: false,
    isSkippable: true,
  },
  {
    key: 'data_import',
    name: 'Data Import',
    description: 'Import initial data',
    order: 11,
    isRequired: false,
    isSkippable: true,
  },
  {
    key: 'security_configuration',
    name: 'Security Configuration',
    description: 'Set up security policies',
    order: 12,
    isRequired: true,
    isSkippable: true,
  },
  {
    key: 'go_live_check',
    name: 'Go-Live Checklist',
    description: 'Complete pre-launch checklist',
    order: 13,
    isRequired: false,
    isSkippable: true,
    dependencies: [
      'admin_creation',
      'schema_initialization',
      'initial_settings',
    ],
  },
];
