export enum PaymentStatus {
  PENDING = 'pending',
  COMPLETED = 'completed',
  FAILED = 'failed',
  CANCELLED = 'cancelled',
  REVERSED = 'reversed',
  REFUNDED = 'refunded',
  PROCESSING = 'processing',
  DECLINED = 'declined',
  ON_HOLD = 'on_hold',
  EXPIRED = 'expired',
  PARTIALLY_REFUNDED = 'partially_refunded',
  AUTHORIZED = 'authorized',
  DECLINED_BY_BANK = 'declined_by_bank',
  DECLINED_BY_USER = 'declined_by_user',
  DECLINED_BY_PROVIDER = 'declined_by_provider',
  DECLINED_BY_FRAUD_CHECK = 'declined_by_fraud_check',
  DECLINED_BY_LIMIT = 'declined_by_limit',
  DECLINED_BY_RISK_CHECK = 'declined_by_risk_check',
  DECLINED_BY_INSUFFICIENT_FUNDS = 'declined_by_insufficient_funds',
  DECLINED_BY_CURRENCY_NOT_SUPPORTED = 'declined_by_currency_not_supported',
  DECLINED_BY_PAYMENT_METHOD_NOT_SUPPORTED = 'declined_by_payment_method_not_supported',
  DECLINED_BY_PAYMENT_GATEWAY = 'declined_by_payment_gateway',
  DECLINED_BY_BANK_ISSUER = 'declined_by_bank_issuer',
  DECLINED_BY_BANK_NETWORK = 'declined_by_bank_network',
  DECLINED_BY_BANK_FRAUD_CHECK = 'declined_by_bank_fraud_check',
  DECLINED_BY_BANK_LIMIT = 'declined_by_bank_limit',
  DECLINED_BY_BANK_RISK_CHECK = 'declined_by_bank_risk_check',
  DECLINED_BY_BANK_INSUFFICIENT_FUNDS = 'declined_by_bank_insufficient_funds',
  DECLINED_BY_BANK_CURRENCY_NOT_SUPPORTED = 'declined_by_bank_currency_not_supported',
  DECLINED_BY_BANK_PAYMENT_METHOD_NOT_SUPPORTED = 'declined_by_bank_payment_method_not_supported',
  DECLINED_BY_BANK_PAYMENT_GATEWAY = 'declined_by_bank_payment_gateway',
  DECLINED_BY_BANK_BANK_ISSUER = 'declined_by_bank_bank_issuer',
  DECLINED_BY_BANK_BANK_NETWORK = 'declined_by_bank_bank_network',
  DECLINED_BY_BANK_BANK_FRAUD_CHECK = 'declined_by_bank_bank_fraud_check',
}

export enum PaymentMethod {
  MOBILE_MONEY = 'mobile_money',
  CREDIT_CARD = 'credit_card',
  DEBIT_CARD = 'debit_card',
  PAYPAL = 'paypal',
  BANK_TRANSFER = 'bank_transfer',
  CRYPTO = 'crypto',
  USSD = 'ussd',
  AGENCY_BANKING = 'agency_banking',
}

export enum Currency {
  KES = 'KES',
  USD = 'USD',
  EUR = 'EUR',
  GBP = 'GBP',
  NGN = 'NGN',
  ZAR = 'ZAR',
  UGX = 'UGX',
  TZS = 'TZS',
  RWF = 'RWF',
}

export enum PaymentProvider {
  MPESA = 'mpesa',
  AIRTEL_MONEY = 'airtel_money',
  EQUITY_BANK = 'equity_bank',
  KCB_BANK = 'kcb_bank',
  COOPERATIVE_BANK = 'cooperative_bank',
  ABSA = 'absa',
  NCBA = 'ncba',
  SAFARICOM = 'safaricom', // for M-PESA APIs, merchant integrations
  PAYPAL = 'paypal',
  FLUTTERWAVE = 'flutterwave',
  PAYSTACK = 'paystack',
  STRIPE = 'stripe',
  COINBASE = 'coinbase',
}
